apiVersion: v1
kind: Service
metadata:
  name: microservice-service
  labels:
    app: microservice
spec:
  selector:
    app: microservice
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
